spring:
  data:
    rest:
      basePath: '/api'
  thymeleaf:
    cache: false
  datasource:
    url: 'jdbc:h2:./devDB;DB_CLOSE_ON_EXIT=FALSE'
#    url: 'jdbc:h2:./prodDB;DB_CLOSE_ON_EXIT=FALSE'
  jpa:
    hibernate:
      ddl-auto: 'update'
liquibase:
  enabled: false