spring:
  data:
    rest:
      basePath: '/api'
  thymeleaf:
    cache: false
  datasource:
    url: 'jdbc:h2:./devDB;DB_CLOSE_ON_EXIT=FALSE'
  jpa:
    hibernate:
      ddl-auto: ''
liquibase:
#  enabled: false